import { createRoot } from "react-dom/client";
import { useEffect, useState } from "react";
import { GoogleGeminiEffect } from "./gemini-effect";
import "./style.css";
import "./analysis.css";
import "./polish.css";

const disclaimer = "Kết quả xổ số là ngẫu nhiên. Thống kê quá khứ không giúp dự đoán kỳ quay sau. Trang này chỉ mang tính tham khảo và giải trí, không liên kết với Vietlott. Chỉ dành cho người từ 18 tuổi trở lên. Hãy chơi có trách nhiệm.";
const nav = ["Trang chủ", "Mega 6/45", "Power 6/55", "Lotto 5/35", "Bản đồ số", "Cấu trúc dữ liệu", "Lọc lịch sử", "Bộ số tham khảo", "Kiểm tra bộ số", "Thống kê", "Máy tính Bao", "Backtest", "Kiến thức", "Nguồn dữ liệu & phương pháp"];
type Draw = { draw_id: number; draw_date: string; numbers: number[]; special?: number | null };

function App() {
  const [page, setPage] = useState(decodeURIComponent(location.hash.slice(1) || "Trang chủ"));
  const eligible = localStorage.getItem("vl-18-plus") === "yes";
  useEffect(() => { const update = () => setPage(decodeURIComponent(location.hash.slice(1) || "Trang chủ")); addEventListener("hashchange", update); return () => removeEventListener("hashchange", update); }, []);
  return <>{!eligible && <section className="gate"><h1>Xác nhận độ tuổi</h1><p>Nội dung chỉ dành cho người từ 18 tuổi trở lên.</p><button onClick={() => { localStorage.setItem("vl-18-plus", "yes"); location.reload(); }}>Tôi từ 18 tuổi trở lên</button></section>}
    <header><div className="topline"><span className="eyebrow">VIETLOTT LAB · DỮ LIỆU CÓ THỂ KIỂM TRA</span><span className="live-pill">● LIVE DATA</span></div><h1>Nhìn rõ lịch sử.<br /><em>Hiểu đúng xác suất.</em></h1><p>Kho lưu trữ kết quả và thống kê trung tính cho các bộ số Vietlott.</p><nav>{nav.map((item) => <a href={`#${item}`} key={item}>{item}</a>)}</nav></header>
    {page === "Trang chủ" && <section className="hero-effect"><GoogleGeminiEffect /><div className="hero-copy"><span>THỐNG KÊ · PHƯƠNG PHÁP · MINH BẠCH</span><h2>Không dự đoán.<br />Chỉ cung cấp bằng chứng.</h2></div></section>}
    <main><Page page={page} /></main><footer>{disclaimer}</footer></>;
}

function Page({ page }: { page: string }) {
  const games = ["Mega 6/45", "Power 6/55", "Lotto 5/35"];
  if (page === "Trang chủ") return <><section className="game-grid">{games.map((game, i) => <article className="game-card" key={game}><span>0{i + 1}</span><h2>{game}</h2><p>Kết quả kỳ quay · tần suất · xác suất</p><a href={`#${game}`}>Xem dữ liệu →</a></article>)}</section><section className="info"><h2>Nguyên tắc của Lab</h2><p>Các kỳ quay là độc lập. Thống kê quá khứ không làm thay đổi xác suất của bộ số tiếp theo.</p></section></>;
  if (games.includes(page)) return <GamePage game={page} />;
  if (page === "Bộ số tham khảo") return <Generator />;
  if (page === "Bản đồ số") return <NumberMap />;
  if (page === "Cấu trúc dữ liệu") return <Structure />;
  if (page === "Lọc lịch sử") return <History />;
  if (page === "Kiểm tra bộ số") return <Checker />;
  if (page === "Thống kê") return <Stats />;
  if (page === "Máy tính Bao") return <Bao />;
  if (page === "Kiến thức") return <section className="info"><h2>Kiến thức</h2><p>Các kỳ quay độc lập. Sai lầm con bạc không làm thay đổi xác suất kỳ sau.</p></section>;
  if (page === "Backtest") return <section className="info"><h2>Backtest</h2><p>Kết quả walk-forward sẽ hiển thị cùng seed, khoảng tin cậy và hiệu chỉnh Holm khi dữ liệu hợp lệ.</p></section>;
  return <section className="info"><h2>{page}</h2><p>Nguồn ưu tiên là trang chính thức; dữ liệu được cache và kiểm tra schema trước khi công bố.</p></section>;
}

function GamePage({ game }: { game: string }) {
  const file = game === "Mega 6/45" ? "mega" : game === "Power 6/55" ? "power" : "lotto535";
  const [draws, setDraws] = useState<Draw[]>([]); const [error, setError] = useState("");
  const load = () => fetch(`${import.meta.env.BASE_URL}data/${file}.json?ts=${Date.now()}`).then((r) => r.ok ? r.json() : Promise.reject(new Error("Không tải được dữ liệu"))).then(setDraws).catch((e) => setError(e.message));
  useEffect(() => { load(); const timer = window.setInterval(load, 300000); return () => window.clearInterval(timer); }, [file]);
  return <section className="info"><p className="eyebrow">DỮ LIỆU TỰ ĐỘNG CẬP NHẬT · MỖI 5 PHÚT</p><h2>{game}</h2>{error && <p className="notice">{error} · đang giữ dữ liệu lần trước nếu có.</p>}{!error && !draws.length && <p>Đang tải dữ liệu…</p>}{draws.length > 0 && <><p>{draws.length.toLocaleString("vi-VN")} kỳ · mới nhất #{String(draws[draws.length - 1].draw_id).padStart(5, "0")} · kiểm tra lúc {new Date().toLocaleTimeString("vi-VN")}</p><div className="table-wrap"><table><thead><tr><th>Kỳ</th><th>Ngày</th><th>Bộ số</th><th>ĐB</th></tr></thead><tbody>{draws.slice(-25).reverse().map((d) => <tr key={d.draw_id}><td>#{String(d.draw_id).padStart(5, "0")}</td><td>{d.draw_date}</td><td>{d.numbers.map((n) => String(n).padStart(2, "0")).join(" · ")}</td><td>{d.special ? String(d.special).padStart(2, "0") : "—"}</td></tr>)}</tbody></table></div></>}</section>;
}

function Generator() {
  const [game, setGame] = useState("Mega 6/45"); const [count, setCount] = useState(3); const [seed, setSeed] = useState("20261008"); const [strategy, setStrategy] = useState("balanced"); const [sets, setSets] = useState<number[][]>([]); const [scoreInfo, setScoreInfo] = useState(""); const [draws, setDraws] = useState<Draw[]>([]);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/${game === "Mega 6/45" ? "mega" : "power"}.json`).then(r => r.json()).then(setDraws).catch(() => setDraws([])); }, [game]);
  const make = () => { let state = [...seed].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7); const next = () => { state = (1664525 * state + 1013904223) >>> 0; return state / 4294967296; }; const max = game === "Mega 6/45" ? 45 : 55; const freq = Array(max + 1).fill(0); draws.forEach(d => d.numbers.forEach(n => { if (n <= max) freq[n]++; })); const maxFreq = Math.max(1, ...freq); const lastSeen = Array(max + 1).fill(draws.length); draws.forEach((d, i) => d.numbers.forEach(n => { if (lastSeen[n] === draws.length) lastSeen[n] = draws.length - i; })); const score = (row: number[]) => { const evens = row.filter(n => n % 2 === 0).length; const sum = row.reduce((a,n) => a+n,0); const balance = evens >= 2 && evens <= 4 ? 1 : 0; const sumScore = sum >= max * .35 && sum <= max * .75 ? 1 : 0; const frequency = row.reduce((a,n) => a + freq[n] / maxFreq, 0) / 6; const gap = row.reduce((a,n) => a + Math.min(lastSeen[n], 40) / 40, 0) / 6; if (strategy === "frequency") return frequency + balance * .15; if (strategy === "gap") return gap + balance * .15; if (strategy === "balanced") return balance + sumScore * .2 + frequency * .1; return next(); }; const candidates: {row:number[];score:number}[] = []; for (let i = 0; i < 1200; i++) { const pool = Array.from({ length: max }, (_, j) => j + 1); const row: number[] = []; while (row.length < 6) { const n = Math.floor(next() * pool.length); row.push(pool.splice(n, 1)[0]); } row.sort((a,b)=>a-b); candidates.push({row, score:score(row)}); } candidates.sort((a,b)=>b.score-a.score); const chosen: number[][] = []; for (const c of candidates) { if (!chosen.some(r => r.some(n => c.row.includes(n)) >= 5)) chosen.push(c.row); if (chosen.length >= count) break; } setSets(chosen); setScoreInfo(draws.length ? `Đã chấm ${candidates.length.toLocaleString("vi-VN")} ứng viên từ ${draws.length.toLocaleString("vi-VN")} kỳ lịch sử; tránh chọn các bộ quá giống nhau.` : "Chưa có dữ liệu lịch sử, đang dùng random baseline."); };
  useEffect(() => { make(); }, [game, count, seed, strategy]);
  const odds = game === "Mega 6/45" ? "1 / 8.145.060" : "1 / 28.989.675";
  return <section className="info"><p className="eyebrow">MONTE CARLO · WALK-FORWARD READY</p><h2>Đề xuất bộ số tham khảo</h2><p>Hệ thống tạo 1.200 ứng viên, chấm theo dữ liệu lịch sử và loại các bộ quá giống nhau. Đây là xếp hạng thống kê, không làm tăng xác suất Jackpot {odds}.</p><div className="generator-controls"><label>Game <select value={game} onChange={(e) => setGame(e.target.value)}><option>Mega 6/45</option><option>Power 6/55</option></select></label><label>Số bộ <input type="number" min="1" max="10" value={count} onChange={(e) => setCount(Math.max(1, Math.min(10, Number(e.target.value))))} /></label><label>Seed <input value={seed} onChange={(e) => setSeed(e.target.value)} /></label><label>Chiến lược <select value={strategy} onChange={(e) => setStrategy(e.target.value)}><option value="balanced">Cân bằng + tổng dãy</option><option value="frequency">Tần suất lịch sử</option><option value="gap">Khoảng cách xuất hiện</option><option value="random">Random baseline</option></select></label></div><button onClick={make}>Đề xuất bộ số</button>{scoreInfo && <p className="success">{scoreInfo}</p>}{sets.map((row, i) => <output className="number-output" key={i}>#{i + 1} · {row.map((n) => String(n).padStart(2, "0")).join(" · ")} <button className="copy-button" onClick={() => navigator.clipboard?.writeText(row.join(" - "))}>Sao chép</button></output>)}</section>;
}

function Checker() { const [value, setValue] = useState(""); const [game, setGame] = useState("Mega 6/45"); const max = game === "Mega 6/45" ? 45 : 55; const nums = value.split(/[,\s-]+/).map(Number).filter(Boolean); const valid = nums.length === 6 && new Set(nums).size === 6 && nums.every(n => n >= 1 && n <= max); return <section className="info"><p className="eyebrow">KIỂM TRA ĐỊNH DẠNG</p><h2>Kiểm tra bộ số</h2><p>Nhập sáu số để kiểm tra tính hợp lệ trước khi lưu hoặc tham khảo.</p><div className="generator-controls"><label>Game <select value={game} onChange={e => setGame(e.target.value)}><option>Mega 6/45</option><option>Power 6/55</option></select></label><label>Bộ số <input className="wide-input" value={value} onChange={e => setValue(e.target.value)} placeholder="Ví dụ: 03 12 18 27 33 45" /></label></div>{value && <p className={valid ? "success" : "notice"}>{valid ? "Bộ số hợp lệ: đủ 6 số khác nhau và đúng phạm vi." : `Chưa hợp lệ: cần đúng 6 số khác nhau trong khoảng 1–${max}.`}</p>}</section>; }

function Stats() { const [draws,setDraws]=useState<Draw[]>([]); const [updated,setUpdated]=useState(""); const [windowSize,setWindowSize]=useState(50); const load=()=>fetch(`${import.meta.env.BASE_URL}data/mega.json?ts=${Date.now()}`).then(r=>r.json()).then(d=>{setDraws(d);setUpdated(new Date().toLocaleTimeString("vi-VN"));}); useEffect(()=>{load();const t=window.setInterval(load,300000);return()=>window.clearInterval(t);},[]); const recent=draws.slice(-windowSize); const rows=Array.from({length:45},(_,i)=>{const n=i+1;const all=draws.filter(d=>d.numbers.includes(n)).length;const recentCount=recent.filter(d=>d.numbers.includes(n)).length;const lastIndex=[...draws].reverse().findIndex(d=>d.numbers.includes(n));const gap=lastIndex<0?"—":lastIndex;const expected=draws.length*6/45;const rate=recent.length?recentCount/recent.length*100:0;const z=draws.length?((all-expected)/Math.sqrt(Math.max(.01,draws.length*(6/45)*(39/45)))):0;return {n,all,recentCount,rate,gap,expected,z};}).sort((a,b)=>b.recentCount-a.recentCount); return <section className="info"><div className="section-heading"><div><p className="eyebrow">PHÂN TÍCH ĐỊNH LƯỢNG · TỰ LÀM MỚI 5 PHÚT</p><h2>Thống kê & phân tích số</h2><p>{draws.length.toLocaleString("vi-VN")} kỳ · dữ liệu tải lúc {updated||"đang tải…"}.</p></div><div className="toolbar"><label>Cửa sổ <select value={windowSize} onChange={e=>setWindowSize(Number(e.target.value))}><option value="25">25 kỳ</option><option value="50">50 kỳ</option><option value="100">100 kỳ</option><option value={draws.length||1572}>Toàn bộ</option></select></label><button onClick={load}>Làm mới</button></div></div><div className="method-note"><strong>Cách đọc:</strong> Tần suất kỳ vọng = số kỳ × 6/45. Z-score chỉ đo độ lệch mô tả so với baseline; không phải xác suất dự đoán kỳ sau.</div><div className="table-wrap analysis-table"><table><thead><tr><th>Số</th><th>{windowSize} kỳ gần nhất</th><th>Tất cả kỳ</th><th>Tỷ lệ gần đây</th><th>Cách kỳ gần nhất</th><th>Baseline kỳ vọng</th><th>Z-score</th></tr></thead><tbody>{rows.map(x=><tr key={x.n}><td><strong className="number-chip">{String(x.n).padStart(2,"0")}</strong></td><td>{x.recentCount}</td><td>{x.all}</td><td>{x.rate.toFixed(1)}%</td><td>{x.gap}</td><td>{x.expected.toFixed(1)}</td><td className={Math.abs(x.z)>=2?"highlight":""}>{x.z.toFixed(2)}</td></tr>)}</tbody></table></div><p className="muted">Cập nhật tự động không đồng nghĩa với dự báo chính xác. Mọi bộ số hợp lệ vẫn có xác suất toán học như nhau.</p></section>; }

function useMegaDraws() { const [draws,setDraws]=useState<Draw[]>([]); useEffect(()=>{const load=()=>fetch(`${import.meta.env.BASE_URL}data/mega.json?ts=${Date.now()}`).then(r=>r.json()).then(setDraws); load(); const t=window.setInterval(load,300000); return()=>window.clearInterval(t);},[]); return draws; }
function NumberMap() { const draws=useMegaDraws(); const counts=Array.from({length:45},(_,i)=>({n:i+1,c:draws.reduce((a,d)=>a+(d.numbers.includes(i+1)?1:0),0)})); const max=Math.max(1,...counts.map(x=>x.c)); return <section className="info"><p className="eyebrow">NGHIÊN CỨU DỮ LIỆU VIETLOTT</p><h2>Bản đồ các con số</h2><p>{draws.length.toLocaleString("vi-VN")} kỳ quay · màu đậm hơn nghĩa là xuất hiện nhiều hơn trong dữ liệu đã tải.</p><div className="number-map">{counts.map(x=><div className="map-cell" style={{backgroundColor:`rgba(138,215,200,${.12+.75*x.c/max})`}} key={x.n}><strong>{String(x.n).padStart(2,"0")}</strong><small>{x.c} lần</small></div>)}</div></section>; }
function Structure() { const draws=useMegaDraws(); const rows=draws.map(d=>{const odd=d.numbers.filter(n=>n%2).length; const low=d.numbers.filter(n=>n<=22).length; const sum=d.numbers.reduce((a,n)=>a+n,0); const consecutive=d.numbers.slice(1).filter((n,i)=>n-d.numbers[i]===1).length; return {odd,low,sum,consecutive};}); const avg=(key:keyof typeof rows[number])=>rows.length?(rows.reduce((a,r)=>a+Number(r[key]),0)/rows.length).toFixed(2):"—"; return <section className="info"><p className="eyebrow">CẤU TRÚC DÃY SỐ</p><h2>Tìm hiểu cấu trúc dữ liệu</h2><p>Trung bình trên {draws.length.toLocaleString("vi-VN")} kỳ · thống kê mô tả, không phải dự đoán.</p><div className="metric-grid"><div><span>Tổng trung bình</span><strong>{avg("sum")}</strong></div><div><span>Số lẻ trung bình</span><strong>{avg("odd")}</strong></div><div><span>Số thấp trung bình</span><strong>{avg("low")}</strong></div><div><span>Số liên tiếp TB</span><strong>{avg("consecutive")}</strong></div></div><h3>Phân bố chẵn/lẻ</h3><div className="structure-bars">{[0,1,2,3,4,5,6].map(odd=><div key={odd}><span>{odd}-{6-odd}</span><i style={{height:`${Math.max(4,rows.filter(r=>r.odd===odd).length/(Math.max(1,rows.length)*.5)*100)}%`}} /></div>)}</div></section>; }
function History() { const draws=useMegaDraws(); const [query,setQuery]=useState(""); const [number,setNumber]=useState(""); const filtered=draws.filter(d=>(!query||String(d.draw_id).includes(query)||d.draw_date.includes(query))&&(!number||d.numbers.includes(Number(number)))); return <section className="info"><p className="eyebrow">BỘ LỌC LỊCH SỬ · TỰ CẬP NHẬT</p><h2>Tra cứu kỳ quay</h2><p>{draws.length.toLocaleString("vi-VN")} kỳ quay được lưu</p><div className="generator-controls"><label>Ngày hoặc mã kỳ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ví dụ: 01570 hoặc 2026-10" /></label><label>Có chứa số <input type="number" min="1" max="45" value={number} onChange={e=>setNumber(e.target.value)} placeholder="01–45" /></label></div><div className="history-list">{filtered.slice(-30).reverse().map(d=><div className="history-row" key={d.draw_id}><span><strong>{d.draw_date}</strong><small>Kỳ #{String(d.draw_id).padStart(5,"0")}</small></span><b>{d.numbers.map(n=>String(n).padStart(2,"0")).join(" · ")}</b></div>)}</div></section>; }
function Bao() { const [n, setN] = useState(7); let tickets = 1; for (let i = 1; i <= 6; i++) tickets = tickets * (n - 6 + i) / i; return <section className="info"><h2>Máy tính Bao Mega 6/45</h2><label>Số số chọn <input type="number" min="6" max="18" value={n} onChange={(e) => setN(Number(e.target.value))} /></label><p>{tickets.toLocaleString("vi-VN")} vé tổ hợp · chi phí tham khảo {(tickets * 10000).toLocaleString("vi-VN")} VNĐ.</p><p>Xác suất Jackpot: 1 / 8.145.060 cho mỗi bộ cơ sở. EV phụ thuộc Jackpot và số người cùng trúng.</p></section>; }

createRoot(document.querySelector("#app")!).render(<App />);
